### ISSUE TITLE
PHP Warning when using Implode on a MultiValueField in a template

### ISSUE THREAD

**Issue by lukereative** [symbiote/silverstripe-multivaluefield#13]
When using Implode in a template on a MultiValueField I get a PHP error (although it still functions correctly returns the expected results)

Example:
If I have a MultiValueField called Fruit and I have 3 values stored 'Banana', 'Apple' and 'Orange'

In my template I use:

```
<h1>My Fruit</h1>
<p>$Fruit.Implode<p>
```

And it is rendered as

```
<h1>My Fruit</h1>
<p>Banana, Apple, Orange<p>
```

It also works with the separator parameter:

```
<h1>My Fruit</h1>
<p>$Fruit.Implode(' ')<p>
```

And it is rendered as

```
<h1>My Fruit</h1>
<p>Banana Apple Orange<p>
```

But in both instances (with or without a parameter) I get an error
`PHP Warning:  implode(): Invalid arguments passed in /site/multivaluefield/code/fields/MultiValueField.php on line 151`

**Comment by robbieaverill** [comment]
Re-tested on SS 3.6.1 and multivaluefield 3.0.0 and this is no longer a problem.

I'm not familiar enough with the history of this module to know, but I suspect that the value saved in the field wasn't stored as a serialized array in your case, which is why the error was thrown and why the commit referenced above would've fixed the issue.

Nonetheless it's an array now, so there's no problem.
